type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Teachers College Fellowship"
subtitle = "Doctoral Fellowship"
date = "2025"
content = "Each year offer between one and three doctoral students, which include tution and a stipend for four years."

[[items]]
title = "Example Award"
subtitle = "Organization"
date = "2024"
content = "Description of the award."
