[site]
title = "Sirui LIU"
description = "PhD student at the Teachers College, Columbia University."
favicon = "/favicon.svg"
last_updated = "November 20, 2025"

[author]
name = "Sirui LIU"
title = "PhD Student"
institution = "Teachers College, Columbia University"
avatar = "/Profile.jpg"
email = "sl5576@tc.columbia.edu"
location = "New York, The United State"
location_url = "https://www.google.com/maps/place/Teachers+College,+Columbia+University/@40.8101611,-73.963032,17z/data=!3m1!4b1!4m14!1m7!3m6!1s0x89c2f7b4ca799cc3:0x7bd148cc31f37026!2sBuilding+528!8m2!3d40.8107802!4d-73.9609155!16s%2Fg%2F11twjf5h56!3m5!1s0x89c2f799eb3e8327:0x9943aa38c2b90ade!8m2!3d40.8101571!4d-73.9604571!16zL20vMDNwN2di?entry=ttu&g_ep=EgoyMDI1MTExNy4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "Room 1055, The 528 Building,",
  "Teachers College, Columbia University, NY, USA."
]

[social]
google_scholar = "https://scholar.google.com/citations?user=9idTRJ4AAAAJ&hl=en&oi=sra"
orcid = "https://orcid.org/0000-0001-8233-9494"
github = "https://github.com"
linkedin = "https://www.linkedin.com/in/sirui-liu-277a08200/"

[features]
enable_likes = true

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
